/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.rs",
    "./index.html",
  ],
  // Safelist for dynamically added classes
  safelist: [
    'loading',
    'loaded',
    'opacity-0',
    'opacity-1',
    // Gradient backgrounds
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'from-slate-900',
    'via-purple-900',
    'to-slate-900',
    'from-yellow-400',
    'to-orange-500',
    'from-blue-500',
    'to-purple-600',
    'from-blue-600',
    'to-purple-600',
    'from-green-500',
    'to-emerald-600',
    'from-green-600',
    'to-emerald-700',
    'from-red-500',
    'to-rose-600',
    'from-red-600',
    'to-rose-700',
    'from-orange-400',
    'to-yellow-500',
    'from-gray-600',
    'to-gray-800',
    // Glassmorphism and backdrop effects
    'backdrop-blur-xl',
    'bg-white/10',
    'bg-white/15',
    'bg-white/20',
    'bg-white/5',
    'bg-black/20',
    'border-white/10',
    'border-white/20',
    'border-white/30',
    // Advanced border radius
    'rounded-2xl',
    'rounded-xl',
    // Advanced shadows
    'shadow-2xl',
    'shadow-lg',
    'hover:shadow-green-500/25',
    'hover:shadow-red-500/25',
    // Advanced spacing and sizing
    'w-10',
    'h-10',
    'w-12',
    'h-12',
    'w-16',
    'h-16',
    'w-2',
    'h-2',
    'space-x-3',
    'space-x-4',
    'space-x-6',
    'space-y-3',
    'space-y-6',
    'mb-6',
    'mt-3',
    'mt-4',
    // Advanced colors
    'text-yellow-300',
    'text-gray-300',
    'text-gray-400',
    'text-blue-100',
    'text-blue-400',
    'text-yellow-400',
    'text-green-400',
    'bg-green-500/20',
    'bg-red-500/20',
    'bg-blue-500/10',
    'bg-blue-500/20',
    'bg-yellow-500/10',
    'bg-yellow-500/20',
    'border-blue-500/20',
    'border-yellow-500/20',
    // Advanced grid and flex
    'md:grid-cols-2',
    'md:grid-cols-3',
    'md:flex-row',
    'flex-col',
    // Advanced transitions and transforms
    'transition-all',
    'transition-colors',
    'transition-opacity',
    'duration-200',
    'duration-300',
    'hover:scale-105',
    'transform',
    'group',
    'group-hover:opacity-100',
    'group-hover:text-yellow-300',
    // Advanced positioning
    'absolute',
    'relative',
    'inset-0',
    'inset-y-0',
    'right-0',
    'pointer-events-none',
    // Advanced text and font
    'bg-clip-text',
    'text-transparent',
    'font-display',
    'antialiased',
    '-webkit-font-smoothing',
    '-moz-osx-font-smoothing',
    // Advanced effects
    'animate-pulse',
    'cursor-pointer',
    'appearance-none',
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:border-transparent',
    'placeholder-gray-400',
    'overflow-hidden',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        accent: {
          50: '#fdf4ff',
          100: '#fae8ff',
          200: '#f5d0fe',
          300: '#f0abfc',
          400: '#e879f9',
          500: '#d946ef',
          600: '#c026d3',
          700: '#a21caf',
          800: '#86198f',
          900: '#701a75',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
