version: '3.8'
services:
  db:
    image: postgres:16
    container_name: local_postgres_db
    restart: always
    environment:
      POSTGRES_USER: leptos_user
      POSTGRES_PASSWORD: leptos_pass
      POSTGRES_DB: leptos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
